### ISSUE TITLE
rake time_sheet:archive_old tests fail

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#635]
```
Failures:
  1) rake time_sheet:archive_old archives open timesheets that are 3 months old
     Failure/Error: expect(time_sheet.status).to eq("closed")
       expected: "closed"
            got: "created"
       (compared using ==)
     # ./spec/tasks/archive_old_timesheets_rake_spec.rb:15:in `block (2 levels) in <top (required)>'
  2) rake time_sheet:archive_old creates and archives a timesheet if the contracts does not have one for that month
     Failure/Error: expect(TimeSheet.count).to eq(1)
       expected: 1
            got: 0
       (compared using ==)
     # ./spec/tasks/archive_old_timesheets_rake_spec.rb:22:in `block (2 levels) in <top (required)>'
Finished in 1 minute 47.81 seconds (files took 4.87 seconds to load)
452 examples, 2 failures
```

https://travis-ci.org/hpi-swt2/wimi-portal/builds/337962125

**Comment by chrisma** [comment]
@tbjoern 2e9f992e242d99f3a54f0c9bad77237f7397f7ae fixed it. Thanks!
